Marksman.sln.DotSettings
Marksman/Marksman.fsproj
Marksman/Semato.fs
Marksman/Server.fs
Tests/Helpers.fs
Tests/ParserTests.fs
Tests/SematoTests.fs
Tests/Tests.fsproj
Tests/WorkspaceTest.fs

Add basic support for single-line semantic tokens. The server now supports both `full` and `range` requests, but NOT `full/delta`. This should be fine, however, as the # of tokens should be low bc. it's only wiki links and reference links.

Support semantic tokens

---

.gitignore
LanguageServerProtocol/LanguageServerProtocol.fs
Marksman/Index.fs
Marksman/Marksman.fsproj
Marksman/Server.fs
Marksman/Text.fs
Marksman/Toc.fs
Tests/DiagTest.fs
Tests/Helpers.fs
Tests/Tests.fsproj
Tests/TocTests.fs

Very basic demonstration of how a "Create TOC" can be implemented.
Note that I don't know F# at all :D 
TODO:
1. Learn F#
2. ~Detect an existing TOC and update it when the code action is invoked (can even put diagnostics on the exact locations saying it's out of date)~
~This is actually non-trivial if done in a non-invasive manner - only heuristic that can possibly exist is "first block of nothing but links in the document" and it can be easily broken. Can also match those links to a set of headings for some overlap number.~

feat: Generate table of contents code action

---

Marksman/Diag.fs
Tests/DiagTest.fs

SFW version of checking for the sneaky whitespace that breaks headings.
The diagnostic points directly at the first nbsp in the heading

Add non-breakable space diagnostic

---

README.md

https://github.com/emacs-lsp/lsp-mode/pull/3632 added marksman support. Let's recommend the official integration in the README.

[doc] Mention Emacs LSP mode integration

---

Makefile
Marksman/Text.fs
Marksman/Workspace.fs
Tests/TextTests.fs

This fix mostly improves the experience in neovim. This is because neovim does
change batching in a way that was most likely to trigger a text sync issue.
The gist of the problem is that when processing a change notification with
several changes we didn't update the linemap after applying each change. This
led to borked linemap and firing assertions down the line.

Fix incremental text sync

---

Marksman.sln.DotSettings
Marksman/Diag.fs
Marksman/Server.fs

The idea is to put the state into an agent/actor and then have 2 ways to access the state:
1. non-exlusively/read-only,
2. exclusively/read-write.
This means that concurrent actions that need non-exclusive access to state will all get their snapshot of immutable state and can then be processed in parallel.
Actions that need state exclusively (e.g. textDocument/didChange) will make other exclusive and non-exlusive actions wait.
In some sense, this is an RWLock but async.
This scheme is less lax wrt reordering than what LSP spec allows, but should be good enough. Particularly, should be better than before as "before" didn't use any asynchrony at all.

infra: Rework server's state management

---

LanguageServerProtocol/Types.fs
Marksman/Server.fs
Marksman/State.fs

PrepareRename needs to be explicitly set in the server's caps based on
client's caps. This wasn't done before due to missing types in
LanguageServerProtocol library and therefore didn't work correctly in
Emacs.

fix: Check client's RenameOptions and signal RenameCapabilities from the server

---

Marksman/Marksman.fsproj
Marksman/Workspace.fs
Tests/WorkspaceTest.fs

Neither Glob nor Dotnet.Glob libraries worked in a reasonable way (e.g. following git's semantics for .gitignore).
Here I try to use Microsoft's extension library for filesystem globbing. Preliminary testing results are encouraging. The problem is that it uses system dependent path handling, which means tests for Windows fail on Unix and vice-versa :(

fix: Try to fix glob eval for ignores

---

Marksman/Server.fs
Marksman/Text.fs
Tests/TextTests.fs

- lsp/fix: Don't use an outdated rangeLength parameter of document/didChange
- lsp/fix: Don't traverse children when building non-hierarchical document symbols

Make Marksman work with Helix editor

---

Marksman/Server.fs
Marksman/Workspace.fs

Previously, the logic was simple: if during state update the diagnostics
for a file didn't change there's no need to re-send it.
This is true, when the file is closed/re-opened: no change, no need to
send diagnostics. However, some (all?) editors drop diagnostics when a
file gets closed.
Now the server checks for this case too and re-sends the diagnotics when
needed.
Resolves #62.

diag/fix: Re-send diagnostics when the document is reopened

---

.config/dotnet-tools.json
.editorconfig
Marksman/CodeActions.fs
Marksman/Misc.fs
Marksman/Server.fs
Marksman/Toc.fs
Tests/Helpers.fs
Tests/MiscTests.fs
Tests/TocTests.fs

- test: Make stripMargin correctly handle mixed line endings
- misc: Bump fantomas version
- ca/toc: Ignore whitespace when checking if TOC is up-to-date

ca/toc: Ignore whitespace when checking if TOC is up-to-date

---

Marksman/Server.fs

Previously, when neither the workspace folders, root_uri, nor `root_path` were provided server would deliberately fail.
This is not the best experience because 
* the users can get confused
* the client can still add workspace folders later via a notification.

infra: Do not fail when neither worspace folders nor workspace root is provided

---

Marksman/Workspace.fs
README.md

Resolves #71
- workspace: Support non-root ignore files
- doc: Update REAMDE re: the ignores

workspace: Support non-root ignore files

---

Marksman/CodeActions.fs
Marksman/Compl.fs
Marksman/Diag.fs
Marksman/Marksman.fsproj
Marksman/Misc.fs
Marksman/Refactor.fs
Marksman/Refs.fs
Marksman/Server.fs
Marksman/State.fs
Marksman/Toc.fs
Marksman/Workspace.fs
Marksman/Workspace.fsi
README.md
Tests/ComplTests.fs
Tests/DiagTest.fs
Tests/Helpers.fs
Tests/MiscTests.fs
Tests/RefsTests.fs
Tests/SematoTests.fs
Tests/TocTests.fs
Tests/WorkspaceTest.fs

WIP: Support single-file mode

---

README.md

nvim-lsp-installer has been discontinued by its author in favor of
maxon.nvim.
This PR updates the README to reflect that.
[link to project status](https://github.com/williamboman/nvim-lsp-installer#%E2%84%B9%EF%B8%8F-project-status)

docs: update readme with mason.nvim

---

README.md

[helix#4399](https://github.com/helix-editor/helix/pull/3499) was merged. After installing the marksman binary, markdown worked in Helix as expected.

Update README re: Helix editor configuration

---

README.md

Just a simple note to help users on MacOS if they get the popup
about Mac not being able to check the software for maliciousness.
Refs: #106

docs: add note about popup on mac

---

Marksman/Config.fs
Marksman/Server.fs
Marksman/Workspace.fs
Marksman/Workspace.fsi
README.md
Tests/ConfigTests.fs
Tests/DiagTest.fs
Tests/Helpers.fs
Tests/Tests.fsproj
Tests/WorkspaceTest.fs
Tests/default.marksman.toml
docs/configuration.md

The purpose of this PR is to add configuration
1. User level config in `~/.config/marksman/config.toml` (or `$HOME\\AppData\\Roaming\\marksman\\config.toml` on Windows)
2. Project-level config in `[project-folder]/.marksman.toml`
Project-level config overrides values in user-level configs.

feat: Add user and project level configuration

---

Marksman/Config.fs
Marksman/Server.fs
README.md

The config option was added earlier. This PR make the code action to take the config into account.

ca: Allow to enable/disable ToC code action

---

Marksman.sln.DotSettings
Marksman/Config.fs
Marksman/Diag.fs
Marksman/Misc.fs
Marksman/Refs.fs
Marksman/Server.fs
Marksman/State.fs
Marksman/Workspace.fs
Marksman/Workspace.fsi
Tests/ConfigTests.fs
Tests/MiscTests.fs
Tests/ParserTests.fs
Tests/RefsTests.fs
Tests/default.marksman.toml
global.json

The idea is to allow setting recognized markdown extensions in a config, e.g.
```
[core]
markdown.file_extensions = ["md", "markdown", "mdx", "mdown"]
```
This will resolve #114 
TODO:

core: Allow configuring recognized markdown file extensions

---

.github/workflows/release.yml
Makefile

Hi, this PR adds a binary for osx-arm64 (M1 Macs) to the release workflow. I tested the build / release process in my own fork, and also downloaded and ran the resulting binary from the release downloads with success. Thanks!

ci: Add cross-compilation for osx-arm64

---

Makefile
Marksman/Marksman.fsproj

The `VERSIONSTRING` parameter for the Makefile is required to be able
to skip the build step that runs `git describe --always --dirty` and
set the version suffix manually.
This change allows the packaging for Homebrew as during the build
process it cannot execute git commands.
This is a optional parameter and will fall back to the git command if
not set specifically.
```bash
make VERSIONSTRING=test DEST=buildir publishTo
```
> Example usage of the parameter, would output a binary with the
> version set to `1.0.0-test`.

ci: add VERSIONSTRING Makefile overwrite parameter

---

LanguageServerProtocol/Types.fs

The spec says it should be an optional property https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentClientCapabilities
NOTE: Upstream the fix https://github.com/ionide/LanguageServerProtocol/blob/main/src/Types.fs#L777

lsp: Make publishDiagnostics an optional capability

---

README.md

Add documentation to install Marksman using the Homebrew homebrew/homebrew-core#118817 Formula.

docs: add Homebrew installation guide

---

.github/workflows/build.yml
.github/workflows/release.yml

Ensures that no deprecated functionalities are used inside of the workflows.
>  **Note**
> I wasn't able to test these workflows in my own repository since GitHub doesn't allow me to run the workflows there, there aren't any breaking changes in these action tasks that affect your workflows as far as I can tell.
Also as a side not it seems like you forgot to delete the `mac-univ-bin` branch.

ci: bump action tasks to newest version

---

Marksman/Compl.fs
Marksman/Refs.fs
Tests/RefsTests.fs

core: Use different code paths for link resolution and completion candidates

---

Marksman/Misc.fs
Tests/MiscTests.fs

While # and [, ] need to be encoded, ( and ) don't seem to have a special meaning in the context of wiki link contents. Let's allow them as-is for now.

[compl] Don't encode parentheses in wiki links text

---

README.md

The package is now available on the stable channel;
It is no longer necessary to manually import from the master branch.
This also clarifies that it works for both Linux and MacOS too.

docs/install: update package availability for nix

---

Marksman/Parser.fs
Tests/ParserTests.fs

This is a workaround for #156 until the upstream gets fixed https://github.com/xoofx/markdig/pull/696

parsing: Workaround an incorrect source span of setext heading

---

Makefile

Fixes #163
I switched to `uname -m` everywhere since on M1 Macs, `uname -p` returns `arm` while `uname -m` returns `arm64`.
Tested on:
aarch64-darwin
aarch64-linux
x86_64-linux

build: fix architecture dection on linux platforms

---

Marksman/Fatality.fs
Marksman/Marksman.fsproj
Marksman/Misc.fs
Marksman/Server.fs
Marksman/State.fs
Marksman/Workspace.fs
Marksman/Workspace.fsi
scripts/marksman-server.sh

Summary:
Marksman core doesn't use exceptions for regular control flow so any
exception originating in the core is basically an assert violation.
Outside of server bugs one potential source of exceptions in core is
bugs in clients (e.g. incremental text sync).
Previously, such exception would cause a thread die a silent death in
the guts of async, followed by the process dying because of the timeout
on async response.
This is not helpful because the original exception gets lost, so good
luck debugging what was wrong.
Now the process will just die right away but it'll output a helpful
message together with the original exception, which makes debugging so
much easier.
Example of a message:
```
---------------------------------------------------------------------------
Marksman encountered a …
```

core: Die with a helpful message when an exception is raised in state update

---

Marksman/Config.fs
Marksman/Server.fs
Tests/ConfigTests.fs
Tests/default.marksman.toml

Incremental text sync is more efficient but has been problematic
historically due to client bugs and protocol lacking necessary
information to enforce stronger validation on the server side.
The option to choose incremental text sync is still there, but the
default now is 'full' where the client is expected to send the full
contents of the document on every change.

[core] Make text sync configurable and use full by default

---

snap/snapcraft.yaml

The dotnet / snap packaging is a bit ridiculous. Dotnet 7 is not available as a package. It's only available as a snap but the snap segfaults on core20 and core22; works only with core18. Oh, and you can't use dotnet plugin because it overrides the dotnet from snap.
This is my attempt to reconcile these issues.

build: Try to make snap build with dotnet7

---

Marksman/Server.fs
Marksman/State.fs
Tests/ServerTests.fs
Tests/StateTests.fs
Tests/Tests.fsproj
scripts/marksman-server.bat
scripts/marksman-server.sh

Marksman allows users configure text sync kind in their config. With no
config marksman defaults to Full text sync. Some clients (e.g. ST) would
like a different default. Now such clients can supply it as part of
initialization options:
```
{
"preferredTextSyncKind": 1|2
}
```
This option has lower precedence than whatever user configures in their
global/workspace-local config file.

client: Allow clients to specify preferred text sync kind

---

Makefile

This will facilitate the life of packagers and be more in line with the current standards, since every distribution
has its own default location for the installation of new packages (for instance Arch prefers to be installed in `/usr/local`, Alpine defaults to `/usr` and so on).

Allow packagers to override directory installation & add uninstall rule

---

Makefile
Marksman/Compl.fs
Marksman/Server.fs
Tests/ComplTests.fs

Now the server returns at most 50 candidates. The response is marked as incomplete when the # is exactly 50, otherwise it's marked complete and the client doesn't need to issue any additional requests.

core: Limit the # of completion candidates returned per request + mark response (in)complete when necessary

---

LanguageServerProtocol/Types.fs
Marksman/CodeActions.fs
Marksman/Config.fs
Marksman/Misc.fs
Marksman/Refactor.fs
Marksman/Server.fs
Tests/RefactorTests.fs
Tests/default.marksman.toml

Here's my first pass at a new code action to create files which are linked, but don't exist in the workspace (i.e. a goto-def on the link would error). Choosing the code action creates the file in the root of the workspace folder.
Closes #219.
A few notes:
- I modified `LanguageServerProtocol/Types.fs` to support the create file operation (and other file resource changes). I added a new type for each type of resource operation, and added them all to a new `[<ErasedUnion>]` sum type `DocumentChange`. This type then replaced `TextDocumentEdit` where appropriate. I'm not 100% sure that this is the best way to go about this, but it works and is fairly neat.
- A particular wart in the above is that each of these new types has the field `Kind: string`; I would rather use the existing type …

Add a code action to create nonexistent linked files

---

Marksman/Parser.fs

fixes #265
It is an easy solution but it should cover at least all cases I can think of :thinking: 
Is there a nicer way for "early returns" in F#?

fix: Don't parse tags inside words & URLs

---

Marksman/Parser.fs
Tests/ParserTests.fs

fixes #267 
As described in the issue this only solves the basic requirements so that nested tags (like in Obsidian) work correctly in terms of references, symbols and auto completion.

feat: Basic support for nested tags

---

Marksman/Doc.fs
Marksman/Doc.fsi
Marksman/Lenses.fs
Marksman/Marksman.fsproj
Marksman/Server.fs
Tests/LensesTests.fs
Tests/Tests.fsproj

This just provides a lens with something like '4 references' next to a header.
Clicking on the lens won't actually do anything yet because command handling needs to be implemented by every client.
This (partially) addresses #28 
NOTE: after #269 references are resolved *incrementally* based on document symbols rather than CSTs; which makes 'find references' requests practically free and lenses very cheap. Before #269 a code lens with references would be very expensive.
TODO:

feat: Add code lenses with '# of references' (server side)

---

Marksman/Names.fs
Tests/RefsTests.fs

fix: InternName.tryAsPath shouldn't crash on `/` root path link

---

Benchmarks/Benchmarks.fsproj
Marksman/Marksman.fsproj
Tests/Tests.fsproj

Serilog can't be upgraded because LSP lib needs v2

deps: Bump versions

---

Marksman/Doc.fs

The warning was long overdue for removal as it didn't reflect how the real editors do versioning (which is said because there's othewise no checksumming to ensure the states are consistent between the client and the server).

misc: Remove a warning about an unexpected version

---

Marksman/Lenses.fs
Marksman/Server.fs
Marksman/State.fs
Tests/LensesTests.fs

When client's experimental.codeLensFindReferences capability is set (only VSCode plugin now), Marksman will output extra data for the code lens command that can be used to implement client-side behavior to show references when clicking on the lens.

feat: Provide reference lens data for VSCode

---

Makefile

Adds support for generating the rid string `freebsd-x64`.

Add support for FreeBSD-amd64

---

Marksman/CodeActions.fs
Marksman/Refs.fs
Marksman/Refs.fsi
Tests/CodeActionTests.fs
Tests/Tests.fsproj

Previously, the code would assume lack of references meant the file doesn't exist. However, for references such as [[file#head]] this would also trigger when there's no `head` heading in an existing file `file`.
When someone used this code action it wiped out the existing file.
Now we extract the doc part and check that the doc exists.

fix: Do not suggest 'Create file' code action for broken heading references

---

Marksman/Config.fs
Marksman/Server.fs
Tests/ConfigTests.fs
Tests/default.marksman.toml

After a conversation about adding support for configuring the number of completion candidates in https://github.com/artempyanykh/marksman/issues/315, I decided to try implementing it.
It is still work in progress, and I'll update the status once it works, and the tests pass.

feat: Add configuration option for setting number of completion candidates

---

README.md

The existing link, <https://github.com/bitsper2nd/LSP-marksman>, throws a 404-not found error. The correct URL is now <https://github.com/sublimelsp/LSP-marksman>.

Update README.md - Fix broken link for Sublime Text

---

README.md

README uses an old link for nvim-lspconfig setup; updated to reflect the new file.

docs: update nvim-lspconfig link

---

Tests/RefactorTests.fs

Stacked PRs:
* #362
* __->__#361
--- --- ---

test: Check replacement text in rename refactor

---

Marksman/Refactor.fs
Tests/RefactorTests.fs

Stacked PRs:
* __->__#362
* #361
--- --- ---
Currently, title-based wiki link completion style is "title-slug". This means that when renaming a title of the doc it should b "new-title" rather than "New Title".

fix: Honor wiki link completion style in rename refactors

---

Marksman/Compl.fs

Stacked PRs:
* __->__#363
--- --- ---
Previously, no kind was provided, which made editors treat these completions like 'Text' completions.
The problem with text completions is that they can be disabled by users due to their noise. Which then leads to confusion as to why Marksman's completion doesn't work in neovim or something.
Example config recommendation: https://github.com/hrsh7th/nvim-cmp/blob/5dce1b778b85c717f6614e3f4da45e9f19f54435/doc/cmp.txt#L663
Possibly fixes: #204

feat: Produce completion items with kind = Reference

---

Marksman/Config.fs
Tests/ConfigTests.fs
Tests/default.marksman.toml

Stacked PRs:
* #371
* #369
* #368
* #367
* __->__#366
* #364
--- --- ---
Previously, "level 1 heading = title" was the default. Now there's a toggle for this.
The config option is not wired yet. This will be done separately.

feat: Add a configuration option to treat level 1 headings as title

---

Benchmarks/Program.fs
Marksman/Ast.fs
Marksman/Config.fs
Marksman/Doc.fs
Marksman/Doc.fsi
Marksman/Folder.fs
Marksman/Folder.fsi
Marksman/Parser.fs
Marksman/Server.fs
Marksman/Structure.fs
Tests/AstTests.fs
Tests/Helpers.fs
Tests/ParserTests.fs
Tests/SematoTests.fs
Tests/WorkspaceTest.fs

Stacked PRs:
* #371
* #369
* #368
* __->__#367
* #366
* #364
--- --- ---
Right now it includes only the extensions. Soon it will be extended with title/header config settings.

refactor: Introduce ParserSetting type

---

Marksman/Folder.fs
Marksman/Folder.fsi
Marksman/Server.fs
Marksman/State.fs

Stacked PRs:
* __->__#380
* #379
* #378
--- --- ---
Sometimes, LSP clients can send bogus folders (CWD, or homedir) as part
of added folders in didChangeWorkspaceFolders. Whenever this happens
marksman treats the root as the real root of the project folders and
recursively scans/indexes mardown documents underneath.This is
problematic when such root is a homedir because it makes marksman scan
too much and potentially fail.
Fixes #377
Potentially, addresses #373 too

fix: Check for a bogus root folder in workspace/didChangeWorkspaceFolders request

---

README.md

I just noticed kak-lsp showed an error about "marksman" not being installed, so i decided to add it here.
I didn't even know kak-lsp had built-in support for this.

Add kakoune to readme.
