artempyanykh/marksman

README.md

Added in https://github.com/williamboman/nvim-lsp-installer/issues/759 / https://github.com/williamboman/nvim-lsp-installer/pull/760

misc: Mention nvim-lsp-installer in README

---

Marksman/Compl.fs
Marksman/Marksman.fsproj
Marksman/Refs.fs
Marksman/Workspace.fs
Tests/RefsTests.fs

feat: Resolve relative paths in inline links

---

README.md

First of all, I'm really digging this project. I use it for writing all my notes in Neovim.
Here I just changed Zeta Note to Marksman in one of the footnotes.
Please, let me know if there's anything I can do to contribute other than code. Sadly I'm not familiar with F#.

misc: Update footnote in README

---

.config/dotnet-tools.json
LanguageServerProtocol/LanguageServerProtocol.fs
LanguageServerProtocol/Server.fs
LanguageServerProtocol/Types.fs
Marksman/Cst.fs
Marksman/Index.fs
Marksman/Marksman.fsproj
Marksman/Misc.fs
Marksman/Parser.fs
Marksman/Refactor.fs
Marksman/Refs.fs
Marksman/Semato.fs
Marksman/Server.fs
Marksman/State.fs
Marksman/Text.fs
Tests/DiagTest.fs
Tests/Helpers.fs
Tests/RefactorTests.fs
Tests/RefsTests.fs
Tests/Tests.fsproj
Tests/TocTests.fs

- misc: Update fantomas to 5.0.0-beta-005
- lsp: Add support for textDocument/prepareRename request
- feat: Implement rename refactor for markdown reference links

feat: Implement rename refactor for markdown reference links

---

.github/workflows/build.yml
Marksman/Marksman.fsproj
Marksman/Misc.fs
Marksman/Workspace.fs
Tests/WorkspaceTest.fs

feat: Support ignore files

---

Marksman/Marksman.fsproj
Tests/Tests.fsproj

- feat: Support ignore files
- misc: Avoid running duplicate GH builds on PRs
- misc: Update deps

misc: Update deps

---

Marksman/Server.fs
Marksman/State.fs

Move diagnostic calculation off of the critical path

---

Marksman/CodeActions.fs
Marksman/Misc.fs
Marksman/Server.fs
Marksman/Toc.fs
Tests/TocTests.fs

ca/fix: Don't suggest to Update TOC when it's up to date

---

README.md

doc: Mention Sublime Text integration

---

Marksman/Index.fs
Marksman/Marksman.fsproj
Marksman/Server.fs
Marksman/Symbols.fs
Tests/SymbolsTests.fs
Tests/Tests.fsproj

Fix the ordering of non-hierarchical symbols

---

Marksman/Server.fs

Resolves #99 
This is a temporary workaround until https://github.com/helix-editor/helix/issues/4436 gets resolved. On init Marksman checks the existence of `.marksman.toml`, `.git`, `.hg`, or `.svn` under a workspace folder. If no such marker exists the folder is considered bogus and all files opened under such a folder will be opened in a single file mode (consequently the folder won't be scanned).
The logic is not 100% bullet-proof, but I'd imagine it should cover 90% of cases.

core: Filter out bogus workspace folders on init

---

README.md

Do the stuff promised in #92
You can take a look over the changes [here](https://github.com/RobWalt/marksman/tree/doc/nix-installation)

Docs for nix installation

---

README.md

...
sorry, i think i missed this minor thing in previous PR...

README.md: Superscript the citation comma

---

.github/workflows/build.yml
.github/workflows/release.yml
LanguageServerProtocol/LanguageServerProtocol.fsproj
Makefile
MarkdigPatches/MarkdigPatches.csproj
Marksman/Marksman.fsproj
Tests/Tests.fsproj
global.json
snap/snapcraft.yaml

- [build] Upgrade to dotnet 7
- [build] Use partial trimming to avoid runtime errors

[build] Upgrade to dotnet 7 (attempt 2)

---

Marksman/Server.fs

In single file mode the initial set of workspace folders may be empty.
Doing minBy on an empty collection raises an exception... which gets
swallowed by dotnet async and effectively causes the server to hang on
init.
This patch does an empty check and also wraps the Initialize method in
try-with (this was the only method of the server that didn't have an
exception handler).

core: Unbreak single file mode

---

.github/workflows/release.yml

Hi,
this PR adds linux ARM64 build. It seems to work in my fork, but creating a GH release fails in my repo, probably due to secret mismatch. 
This should close https://github.com/artempyanykh/marksman/issues/98
Cheers,
jos

feat: arm64 build

---

Marksman/Diag.fs
Marksman/Names.fs
Marksman/Names.fsi
Marksman/Refs.fs
Tests/RefsTests.fs

fix: Url decode link text before resolving

---

Marksman/Names.fs
Marksman/Paths.fs
Marksman/Paths.fsi
Marksman/Server.fs
Marksman/Workspace.fs
Tests/DiagTest.fs
Tests/PathsTests.fs
Tests/StateTests.fs
Tests/WorkspaceTest.fs

fix: Fix path resolution in single-file mode

---

LanguageServerProtocol/Client.fs
LanguageServerProtocol/FsLibLog.fs
LanguageServerProtocol/JsonRpc.fs
LanguageServerProtocol/JsonUtils.fs
LanguageServerProtocol/LanguageServerProtocol.fs
LanguageServerProtocol/LanguageServerProtocol.fsproj
LanguageServerProtocol/Server.fs
LanguageServerProtocol/Types.fs
Marksman/Compl.fs
Marksman/Doc.fs
Marksman/Marksman.fsproj
Marksman/Server.fs
Marksman/State.fs
Marksman/Symbols.fs
Marksman/Workspace.fs
Tests/ComplTests.fs
Tests/SymbolsTests.fs
Tests/Tests.fsproj
Tests/WorkspaceTest.fs

This corresponds to v0.4.21 with a few patches on top https://github.com/artempyanykh/LanguageServerProtocol/commit/df8b56eceaea10f5e7a05b906ef914484d5b3ad2

deps: Pull latest Ionide.LanguageServerProtocol

---

Marksman/Paths.fs
Tests/PathsTests.fs

fix: Use UTF8 when encoding paths

---

Tests/default.marksman.toml

fix minor typo

---

Marksman/Conn.fs
Marksman/Syms.fs
Tests/ConnTest.fs

Stacked PRs:
* #344
* #343
* __->__#345
--- --- ---

conn: Fix incremental update when a new title-ish is added

---

Marksman/Conn.fs

Stacked PRs:
* #344
* __->__#343
* #345
--- --- ---

conn: Speed up finding relevant scoped defs

---

Marksman/Syms.fs
Tests/ConnTest.fs

Stacked PRs:
* __->__#344
* #343
* #345
--- --- ---

conn: Fix incremental update with ambiguous section refs

---

.config/dotnet-tools.json

Stacked PRs:
* #346
* __->__#347
--- --- ---

fmt: Update fantomas to 6.3.16

---

Benchmarks/Benchmarks.fsproj

Stacked PRs:
* #352
* #351
* #350
* __->__#349
--- --- ---

deps: Update BenchmarkDotNet

---

Benchmarks/Program.fs

Stacked PRs:
* #352
* #351
* __->__#350
* #349
--- --- ---

bench: Update benchmark results

---

Tests/Tests.fsproj

Stacked PRs:
* #352
* __->__#351
* #350
* #349
--- --- ---

deps: Update Tests dependencies

---

MarkdigPatches/MarkdigPatches.csproj
Marksman/Marksman.fsproj

Stacked PRs:
* __->__#352
* #351
* #350
* #349
--- --- ---

deps: Update Marksman deps

---

Marksman/Mapping.fs

Stacked PRs:
* #357
* #358
* #356
* __->__#355
* #354
--- --- ---

refactor: Add member interface to Mapping

---

LanguageServerProtocol/LanguageServerProtocol.fsproj

Stacked PRs:
* #357
* #358
* __->__#356
* #355
* #354
--- --- ---

deps: Update Newtonsoft.Json

---

Marksman/Config.fs
Marksman/Folder.fs

Stacked PRs:
* #371
* #369
* __->__#368
* #367
* #366
* #364
--- --- ---
The setting is not used anywhere just yet.

misc: Propagate titleFromHeading to parser settings

---

docs/features.md

Stacked PRs:
* __->__#371
* #369
* #368
* #367
* #366
* #364
--- --- ---

doc: Update features.md with info on the new `core.title_from_heading` setting

---

scripts/marksman-server.sh

Stacked PRs:
* #380
* #379
* __->__#378
--- --- ---

misc: Make marksman-server.sh work from a symlink

---

Marksman/Folder.fs

Stacked PRs:
* #380
* __->__#379
* #378
--- --- ---

misc: Change folder load log level to info

---

Marksman/Config.fs
Marksman/Cst.fs
Marksman/Parser.fs
Tests/AstTests.fs
Tests/ConfigTests.fs
Tests/default.marksman.toml

This closes #383.
I don't know F#, please feel free to nitpick.

heading ID disambiguation according to GLFM spec

---

README.md

Arguably this doesn't warrant a new entry as it's supported OOTB, but now it's at least documented that it works and does it well :)

[docs] document integration with Zed

---

README.md

The PR mentioned there has been merged a long time ago.

Update the Ale section
